import { StyleSheet, Dimensions } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  scrollContent: {
    paddingHorizontal: width * 0.001,  // Responsive horizontal padding
    paddingBottom: 10,
    marginTop: 10,
  },
  horizontalScroll: {
    marginBottom: 20,
  },
  summaryCard: {
    backgroundColor: '#1C1C1C',
    padding: 15,
    borderRadius: 12,
    marginRight: 10,
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
    width: width * 0.8,  // Responsive width
    height: 155,
  },
  summaryCardTitle: {
    fontSize: RFValue(18),
    color: '#FFB74D',
    fontFamily: 'Montserrat-Bold',
    marginBottom: 10,
  },
  summaryCardDistance: {
    fontSize: RFValue(16),
    color: '#E0E0E0',
    fontFamily: 'Montserrat-Regular',
    marginBottom: 5,
  },
  summaryCardTime: {
    fontSize: RFValue(14),
    color: '#E0E0E0',
    fontFamily: 'Montserrat-Regular',
  },
  summaryContainer: {
    paddingHorizontal: width * 0.03,  // Responsive horizontal padding
    marginBottom: 20,
    backgroundColor: '#1C1C1C',
    padding: 15,
    borderRadius: 12,
    marginTop: 10,
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  summaryTitle: {
    fontSize: RFValue(18),
    color: '#FFB74D',
    fontFamily: 'Montserrat-Bold',
    marginBottom: 10,
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: RFValue(16),
    color: '#E0E0E0',
    fontFamily: 'Montserrat-Regular',
  },
  summaryValue: {
    fontSize: RFValue(16),
    color: '#FFB74D',
    fontFamily: 'Montserrat-Bold',
  },
  filterContainer: {
    paddingHorizontal: width * 0.003,  // Responsive horizontal padding
    marginBottom: 20,
    marginTop: 10,
  },
  filterLabel: {
    color: '#F0F0F0',
    marginBottom: 10,
    fontFamily: 'Montserrat-SemiBold',
    fontSize: RFValue(16),
  },
  filterDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C1C1C',
    padding: 12,
    borderRadius: 12,
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  filterText: {
    color: '#E0E0E0',
    fontSize: RFValue(16),
    fontFamily: 'Montserrat-Regular',
  },
  arrow: {
    color: '#E0E0E0',
    fontSize: RFValue(16),
  },
  quickLinksContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  quickLink: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    borderColor: '#444',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  quickLinkText: {
    color: '#E0E0E0',
    fontSize: RFValue(13),
    fontFamily: 'Montserrat-Regular',
  },
  calendarContainer: {
    backgroundColor: '#1C1C1C',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  doneButton: {
    backgroundColor: '#FFB74D',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    borderColor: '#F57C00',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  doneButtonText: {
    color: '#0A0A0A',
    fontSize: RFValue(16),
    fontFamily: 'Montserrat-Bold',
  },
  searchContainer: {
    paddingHorizontal: width * 0.03,  // Responsive horizontal padding
    marginTop: 10,
    marginBottom: 20,
  },
  searchInput: {
    backgroundColor: '#1C1C1C',
    color: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 45,
    fontSize: RFValue(16),
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: RFValue(22),
    fontFamily: 'Montserrat-Bold',
    color: '#FFB74D',
  },
  logButton: {
    backgroundColor: '#FFB74D',
    borderRadius: 50,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  logButtonText: {
    fontSize: RFValue(22),
    color: '#0A0A0A',
    fontFamily: 'Montserrat-Bold',
  },
  sessionContainer: {
    backgroundColor: '#1C1C1C',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderColor: '#333',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  sessionDate: {
    fontSize: RFValue(16),
    color: '#FFB74D',
    marginBottom: 5,
    fontFamily: 'Montserrat-SemiBold',
  },
  sessionDetail: {
    fontSize: RFValue(14),
    color: '#E0E0E0',
    marginBottom: 2,
    fontFamily: 'Montserrat-Regular',
  },
  noResultsText: {
    color: '#E0E0E0',
    textAlign: 'center',
    marginTop: 20,
    fontFamily: 'Montserrat-Regular',
  },
  aiButton: {
    position: 'absolute',
    bottom: 50,
    left: 10,
    right: 10,
    backgroundColor: '#00bfae',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  aiButtonText: {
    fontSize: RFValue(18),
    color: '#0A0A0A',
    fontFamily: 'Montserrat-Bold',
  },
});

export default styles;
